#ifndef YAGLPP_NO_MSVC_H
#define YAGLPP_NO_MSVC_H

#ifdef __ATTR_SAL
	#error "Microsoft SAL header cannot be included in non-MSVC environment"
#endif

//============================================================================
//   Structural Layer:
//============================================================================

#define _At_(target, annos) ((void)0)
#define _At_buffer_(target, iter, bound, annos) ((void)0)
#define _When_(expr, annos) ((void)0)
#define _Group_(annos) ((void)0)
#define _GrouP_(annos) ((void)0)
#define _Success_(expr) ((void)0)
#define _Return_type_success_(expr) ((void)0)
#define _On_failure_(annos) ((void)0)
#define _Always_(annos) ((void)0)
#define _Use_decl_annotations_ ((void)0)
#define _Notref_ ((void)0)
#define _Pre_defensive_ ((void)0)
#define _Post_defensive_ ((void)0)
#define _In_defensive_(annotes) ((void)0)
#define _Out_defensive_(annotes) ((void)0)
#define _Inout_defensive_(annotes) ((void)0)

//============================================================================
//   _In_/_Out_ Layer:
//============================================================================

#define _Reserved_ ((void)0)
#define _Const_ ((void)0)
#define _In_ ((void)0)
#define _In_opt_ ((void)0)
#define _In_z_ ((void)0)
#define _In_opt_z_ ((void)0)
#define _In_reads_(size) ((void)0)
#define _In_reads_opt_(size) ((void)0)
#define _In_reads_bytes_(size) ((void)0)
#define _In_reads_bytes_opt_(size) ((void)0)
#define _In_reads_z_(size) ((void)0)
#define _In_reads_opt_z_(size) ((void)0)
#define _In_reads_or_z_(size) ((void)0)
#define _In_reads_or_z_opt_(size) ((void)0)
#define _In_reads_to_ptr_(ptr) ((void)0)
#define _In_reads_to_ptr_opt_(ptr) ((void)0)
#define _In_reads_to_ptr_z_(ptr) ((void)0)
#define _In_reads_to_ptr_opt_z_(ptr) ((void)0)

#define _Out_ ((void)0)
#define _Out_opt_ ((void)0)
#define _Out_writes_(size) ((void)0)
#define _Out_writes_opt_(size) ((void)0)
#define _Out_writes_bytes_(size) ((void)0)
#define _Out_writes_bytes_opt_(size) ((void)0)
#define _Out_writes_z_(size) ((void)0)
#define _Out_writes_opt_z_(size) ((void)0)
#define _Out_writes_to_(size, count) ((void)0)
#define _Out_writes_to_opt_(size, count) ((void)0)
#define _Out_writes_all_(size) ((void)0)
#define _Out_writes_all_opt_(size) ((void)0)
#define _Out_writes_bytes_to_(size, count) ((void)0)
#define _Out_writes_bytes_to_opt_(size, count) ((void)0)
#define _Out_writes_bytes_all_(size) ((void)0)
#define _Out_writes_bytes_all_opt_(size) ((void)0)
#define _Out_writes_to_ptr_(ptr) ((void)0)
#define _Out_writes_to_ptr_opt_(ptr) ((void)0)
#define _Out_writes_to_ptr_z_(ptr) ((void)0)
#define _Out_writes_to_ptr_opt_z_(ptr) ((void)0)

#define _Inout_ ((void)0)
#define _Inout_opt_ ((void)0)
#define _Inout_z_ ((void)0)
#define _Inout_opt_z_ ((void)0)
#define _Inout_updates_(size) ((void)0)
#define _Inout_updates_opt_(size) ((void)0)
#define _Inout_updates_z_(size) ((void)0)
#define _Inout_updates_opt_z_(size) ((void)0)
#define _Inout_updates_to_(size, count) ((void)0)
#define _Inout_updates_to_opt_(size, count) ((void)0)
#define _Inout_updates_all_(size) ((void)0)
#define _Inout_updates_all_opt_(size) ((void)0)
#define _Inout_updates_bytes_(size) ((void)0)
#define _Inout_updates_bytes_opt_(size) ((void)0)
#define _Inout_updates_bytes_to_(size, count) ((void)0)
#define _Inout_updates_bytes_to_opt_(size, count) ((void)0)
#define _Inout_updates_bytes_all_(size) ((void)0)
#define _Inout_updates_bytes_all_opt_(size) ((void)0)

#define _COM_Outptr_ ((void)0)
#define _COM_Outptr_result_maybenull_ ((void)0)
#define _COM_Outptr_opt_ ((void)0)
#define _COM_Outptr_opt_result_maybenull_ ((void)0)

#define _Outptr_ ((void)0)
#define _Outptr_result_maybenull_ ((void)0)
#define _Outptr_opt_ ((void)0)
#define _Outptr_opt_result_maybenull_ ((void)0)
#define _Outptr_result_z_ ((void)0)
#define _Outptr_opt_result_z_ ((void)0)
#define _Outptr_result_maybenull_z_ ((void)0)
#define _Outptr_opt_result_maybenull_z_ ((void)0)
#define _Outptr_result_nullonfailure_ ((void)0)
#define _Outptr_opt_result_nullonfailure_ ((void)0)

#define _Outptr_result_buffer_(size) ((void)0)
#define _Outptr_opt_result_buffer_(size) ((void)0)
#define _Outptr_result_buffer_to_(size, count) ((void)0)
#define _Outptr_opt_result_buffer_to_(size, count) ((void)0)
#define _Outptr_result_buffer_all_(size) ((void)0)
#define _Outptr_opt_result_buffer_all_(size) ((void)0)
#define _Outptr_result_buffer_maybenull_(size) ((void)0)
#define _Outptr_opt_result_buffer_maybenull_(size) ((void)0)
#define _Outptr_result_buffer_to_maybenull_(size, count) ((void)0)
#define _Outptr_opt_result_buffer_to_maybenull_(size, count) ((void)0)
#define _Outptr_result_buffer_all_maybenull_(size) ((void)0)
#define _Outptr_opt_result_buffer_all_maybenull_(size) ((void)0)
#define _Outptr_result_bytebuffer_(size) ((void)0)
#define _Outptr_opt_result_bytebuffer_(size) ((void)0)
#define _Outptr_result_bytebuffer_to_(size, count) ((void)0)
#define _Outptr_opt_result_bytebuffer_to_(size, count) ((void)0)
#define _Outptr_result_bytebuffer_all_(size) ((void)0)
#define _Outptr_opt_result_bytebuffer_all_(size) ((void)0)
#define _Outptr_result_bytebuffer_maybenull_(size) ((void)0)
#define _Outptr_opt_result_bytebuffer_maybenull_(size) ((void)0)
#define _Outptr_result_bytebuffer_to_maybenull_(size, count) ((void)0)
#define _Outptr_opt_result_bytebuffer_to_maybenull_(size, count) ((void)0)
#define _Outptr_result_bytebuffer_all_maybenull_(size) ((void)0)
#define _Outptr_opt_result_bytebuffer_all_maybenull_(size) ((void)0)

#define _Outref_ ((void)0)
#define _Outref_result_maybenull_ ((void)0)
#define _Outref_result_buffer_(size) ((void)0)
#define _Outref_result_bytebuffer_(size) ((void)0)
#define _Outref_result_buffer_to_(size, count) ((void)0)
#define _Outref_result_bytebuffer_to_(size, count) ((void)0)
#define _Outref_result_buffer_all_(size) ((void)0)
#define _Outref_result_bytebuffer_all_(size) ((void)0)
#define _Outref_result_buffer_maybenull_(size) ((void)0)
#define _Outref_result_bytebuffer_maybenull_(size) ((void)0)
#define _Outref_result_buffer_to_maybenull_(size, count) ((void)0)
#define _Outref_result_bytebuffer_to_maybenull_(size, count) ((void)0)
#define _Outref_result_buffer_all_maybenull_(size) ((void)0)
#define _Outref_result_bytebuffer_all_maybenull_(size) ((void)0)
#define _Outref_result_nullonfailure_ ((void)0)

#define _Result_nullonfailure_ ((void)0)
#define _Result_zeroonfailure_ ((void)0)

//============================================================================
// _Ret_ annotations
//============================================================================

#define _Ret_z_ ((void)0)
#define _Ret_maybenull_z_ ((void)0)
#define _Ret_notnull_ ((void)0)
#define _Ret_maybenull_ ((void)0)
#define _Ret_null_ ((void)0)
#define _Ret_valid_ ((void)0)
#define _Ret_writes_(size) ((void)0)
#define _Ret_writes_z_(size) ((void)0)
#define _Ret_writes_bytes_(size) ((void)0)
#define _Ret_writes_maybenull_(size) ((void)0)
#define _Ret_writes_maybenull_z_(size) ((void)0)
#define _Ret_writes_bytes_maybenull_(size) ((void)0)
#define _Ret_writes_to_(size, count) ((void)0)
#define _Ret_writes_bytes_to_(size, count) ((void)0)
#define _Ret_writes_to_maybenull_(size, count) ((void)0)
#define _Ret_writes_bytes_to_maybenull_(size, count) ((void)0)

#define _Points_to_data_ ((void)0)
#define _Literal_ ((void)0)
#define _Notliteral_ ((void)0)
#define _Check_return_ ((void)0)
#define _Must_inspect_result_ ((void)0)
#define _Printf_format_string_ ((void)0)
#define _Scanf_format_string_ ((void)0)
#define _Scanf_s_format_string_ ((void)0)
#define _Format_string_impl_(kind, where) ((void)0)
#define _Printf_format_string_params_(x) ((void)0)
#define _Scanf_format_string_params_(x) ((void)0)
#define _Scanf_s_format_string_params_(x) ((void)0)

#define _In_range_(lb, ub) ((void)0)
#define _Out_range_(lb, ub) ((void)0)
#define _Ret_range_(lb, ub) ((void)0)
#define _Deref_in_range_(lb, ub) ((void)0)
#define _Deref_out_range_(lb, ub) ((void)0)
#define _Deref_ret_range_(lb, ub) ((void)0)
#define _Pre_equal_to_(expr) ((void)0)
#define _Post_equal_to_(expr) ((void)0)
#define _Unchanged_(e) ((void)0)
#define _Pre_satisfies_(cond) ((void)0)
#define _Post_satisfies_(cond) ((void)0)
#define _Struct_size_bytes_(size) ((void)0)

#define _Field_size_(size) ((void)0)
#define _Field_size_opt_(size) ((void)0)
#define _Field_size_part_(size, count) ((void)0)
#define _Field_size_part_opt_(size, count) ((void)0)
#define _Field_size_full_(size) ((void)0)
#define _Field_size_full_opt_(size) ((void)0)
#define _Field_size_bytes_(size) ((void)0)
#define _Field_size_bytes_opt_(size) ((void)0)
#define _Field_size_bytes_part_(size, count) ((void)0)
#define _Field_size_bytes_part_opt_(size, count) ((void)0)
#define _Field_size_bytes_full_(size) ((void)0)
#define _Field_size_bytes_full_opt_(size) ((void)0)
#define _Field_z_ ((void)0)
#define _Field_range_(min, max) ((void)0)

//============================================================================
//   _Pre_/_Post_ Layers:
//============================================================================

#define _Pre_ ((void)0)
#define _Post_ ((void)0)
#define _Valid_ ((void)0)
#define _Notvalid_ ((void)0)
#define _Maybevalid_ ((void)0)
#define _Readable_bytes_(size) ((void)0)
#define _Readable_elements_(size) ((void)0)
#define _Writable_bytes_(size) ((void)0)
#define _Writable_elements_(size) ((void)0)
#define _Null_terminated_ ((void)0)
#define _NullNull_terminated_ ((void)0)
#define _Pre_readable_size_(size) ((void)0)
#define _Pre_writable_size_(size) ((void)0)
#define _Pre_readable_byte_size_(size) ((void)0)
#define _Pre_writable_byte_size_(size) ((void)0)
#define _Post_readable_size_(size) ((void)0)
#define _Post_writable_size_(size) ((void)0)
#define _Post_readable_byte_size_(size) ((void)0)
#define _Post_writable_byte_size_(size) ((void)0)
#define _Null_ ((void)0)
#define _Notnull_ ((void)0)
#define _Maybenull_ ((void)0)

#define _Pre_z_ ((void)0)
#define _Pre_valid_ ((void)0)
#define _Pre_opt_valid_ ((void)0)
#define _Pre_invalid_ ((void)0)
#define _Pre_unknown_ ((void)0)
#define _Pre_notnull_ ((void)0)
#define _Pre_maybenull_ ((void)0)
#define _Pre_null_ ((void)0)

#define _Post_z_ ((void)0)
#define _Post_valid_ ((void)0)
#define _Post_invalid_ ((void)0)
#define _Post_ptr_invalid_ ((void)0)
#define _Post_notnull_ ((void)0)
#define _Post_null_ ((void)0)
#define _Post_maybenull_ ((void)0)
#define _Prepost_z_ ((void)0)

//============================================================================
//   Definitions for macros defined for VS2010 and earlier.
//============================================================================

#define _In_count_(size) ((void)0)
#define _In_opt_count_(size) ((void)0)
#define _In_bytecount_(size) ((void)0)
#define _In_opt_bytecount_(size) ((void)0)
#define _In_count_c_(size) ((void)0)
#define _In_opt_count_c_(size) ((void)0)
#define _In_bytecount_c_(size) ((void)0)
#define _In_opt_bytecount_c_(size) ((void)0)
#define _In_z_count_(size) ((void)0)
#define _In_opt_z_count_(size) ((void)0)
#define _In_z_bytecount_(size) ((void)0)
#define _In_opt_z_bytecount_(size) ((void)0)
#define _In_z_count_c_(size) ((void)0)
#define _In_opt_z_count_c_(size) ((void)0)
#define _In_z_bytecount_c_(size) ((void)0)
#define _In_opt_z_bytecount_c_(size) ((void)0)
#define _In_ptrdiff_count_(size) ((void)0)
#define _In_opt_ptrdiff_count_(size) ((void)0)
#define _In_count_x_(size) ((void)0)
#define _In_opt_count_x_(size) ((void)0)
#define _In_bytecount_x_(size) ((void)0)
#define _In_opt_bytecount_x_(size) ((void)0)

#define _Out_cap_(size) ((void)0)
#define _Out_opt_cap_(size) ((void)0)
#define _Out_bytecap_(size) ((void)0)
#define _Out_opt_bytecap_(size) ((void)0)
#define _Out_cap_c_(size) ((void)0)
#define _Out_opt_cap_c_(size) ((void)0)
#define _Out_bytecap_c_(size) ((void)0)
#define _Out_opt_bytecap_c_(size) ((void)0)
#define _Out_cap_m_(mult,size) ((void)0)
#define _Out_opt_cap_m_(mult,size) ((void)0)
#define _Out_z_cap_m_(mult,size) ((void)0)
#define _Out_opt_z_cap_m_(mult,size) ((void)0)
#define _Out_ptrdiff_cap_(size) ((void)0)
#define _Out_opt_ptrdiff_cap_(size) ((void)0)
#define _Out_cap_x_(size) ((void)0)
#define _Out_opt_cap_x_(size) ((void)0)
#define _Out_bytecap_x_(size) ((void)0)
#define _Out_opt_bytecap_x_(size) ((void)0)
#define _Out_z_cap_(size) ((void)0)
#define _Out_opt_z_cap_(size) ((void)0)
#define _Out_z_bytecap_(size) ((void)0)
#define _Out_opt_z_bytecap_(size) ((void)0)
#define _Out_z_cap_c_(size) ((void)0)
#define _Out_opt_z_cap_c_(size) ((void)0)
#define _Out_z_bytecap_c_(size) ((void)0)
#define _Out_opt_z_bytecap_c_(size) ((void)0)
#define _Out_z_cap_x_(size) ((void)0)
#define _Out_opt_z_cap_x_(size) ((void)0)
#define _Out_z_bytecap_x_(size) ((void)0)
#define _Out_opt_z_bytecap_x_(size) ((void)0)
#define _Out_cap_post_count_(cap, count) ((void)0)
#define _Out_opt_cap_post_count_(cap, count) ((void)0)
#define _Out_bytecap_post_bytecount_(cap, count) ((void)0)
#define _Out_opt_bytecap_post_bytecount_(cap, count) ((void)0)
#define _Out_z_cap_post_count_(cap, count) ((void)0)
#define _Out_opt_z_cap_post_count_(cap, count) ((void)0)
#define _Out_z_bytecap_post_bytecount_(cap, count) ((void)0)
#define _Out_opt_z_bytecap_post_bytecount_(cap, count) ((void)0)
#define _Out_capcount_(capcount) ((void)0)
#define _Out_opt_capcount_(capcount) ((void)0)
#define _Out_bytecapcount_(capcount) ((void)0)
#define _Out_opt_bytecapcount_(capcount) ((void)0)
#define _Out_capcount_x_(capcount) ((void)0)
#define _Out_opt_capcount_x_(capcount) ((void)0)
#define _Out_bytecapcount_x_(capcount) ((void)0)
#define _Out_opt_bytecapcount_x_(capcount) ((void)0)
#define _Out_z_capcount_(capcount) ((void)0)
#define _Out_opt_z_capcount_(capcount) ((void)0)
#define _Out_z_bytecapcount_(capcount) ((void)0)
#define _Out_opt_z_bytecapcount_(capcount) ((void)0)

#define _Inout_count_(size) ((void)0)
#define _Inout_opt_count_(size) ((void)0)
#define _Inout_bytecount_(size) ((void)0)
#define _Inout_opt_bytecount_(size) ((void)0)
#define _Inout_count_c_(size) ((void)0)
#define _Inout_opt_count_c_(size) ((void)0)
#define _Inout_bytecount_c_(size) ((void)0)
#define _Inout_opt_bytecount_c_(size) ((void)0)
#define _Inout_z_count_(size) ((void)0)
#define _Inout_opt_z_count_(size) ((void)0)
#define _Inout_z_bytecount_(size) ((void)0)
#define _Inout_opt_z_bytecount_(size) ((void)0)
#define _Inout_z_count_c_(size) ((void)0)
#define _Inout_opt_z_count_c_(size) ((void)0)
#define _Inout_z_bytecount_c_(size) ((void)0)
#define _Inout_opt_z_bytecount_c_(size) ((void)0)
#define _Inout_ptrdiff_count_(size) ((void)0)
#define _Inout_opt_ptrdiff_count_(size) ((void)0)
#define _Inout_count_x_(size) ((void)0)
#define _Inout_opt_count_x_(size) ((void)0)
#define _Inout_bytecount_x_(size) ((void)0)
#define _Inout_opt_bytecount_x_(size) ((void)0)
#define _Inout_cap_(size) ((void)0)
#define _Inout_opt_cap_(size) ((void)0)
#define _Inout_bytecap_(size) ((void)0)
#define _Inout_opt_bytecap_(size) ((void)0)
#define _Inout_cap_c_(size) ((void)0)
#define _Inout_opt_cap_c_(size) ((void)0)
#define _Inout_bytecap_c_(size) ((void)0)
#define _Inout_opt_bytecap_c_(size) ((void)0)
#define _Inout_cap_x_(size) ((void)0)
#define _Inout_opt_cap_x_(size) ((void)0)
#define _Inout_bytecap_x_(size) ((void)0)
#define _Inout_opt_bytecap_x_(size) ((void)0)
#define _Inout_z_cap_(size) ((void)0)
#define _Inout_opt_z_cap_(size) ((void)0)
#define _Inout_z_bytecap_(size) ((void)0)
#define _Inout_opt_z_bytecap_(size) ((void)0)
#define _Inout_z_cap_c_(size) ((void)0)
#define _Inout_opt_z_cap_c_(size) ((void)0)
#define _Inout_z_bytecap_c_(size) ((void)0)
#define _Inout_opt_z_bytecap_c_(size) ((void)0)
#define _Inout_z_cap_x_(size) ((void)0)
#define _Inout_opt_z_cap_x_(size) ((void)0)
#define _Inout_z_bytecap_x_(size) ((void)0)
#define _Inout_opt_z_bytecap_x_(size) ((void)0)

#define _Ret_ ((void)0)
#define _Ret_opt_ ((void)0)
#define _In_bound_ ((void)0)
#define _Out_bound_ ((void)0)
#define _Ret_bound_ ((void)0)
#define _Deref_in_bound_ ((void)0)
#define _Deref_out_bound_ ((void)0)
#define _Deref_inout_bound_ ((void)0)
#define _Deref_ret_bound_ ((void)0)
#define _Deref_out_ ((void)0)
#define _Deref_out_opt_ ((void)0)
#define _Deref_opt_out_ ((void)0)
#define _Deref_opt_out_opt_ ((void)0)
#define _Deref_out_z_ ((void)0)
#define _Deref_out_opt_z_ ((void)0)
#define _Deref_opt_out_z_ ((void)0)
#define _Deref_opt_out_opt_z_ ((void)0)

//============================================================================
//   _Deref_pre_/_Deref_post_ ---
//============================================================================

#define _Deref_pre_z_ ((void)0)
#define _Deref_pre_opt_z_ ((void)0)
#define _Deref_pre_cap_(size) ((void)0)
#define _Deref_pre_opt_cap_(size) ((void)0)
#define _Deref_pre_bytecap_(size) ((void)0)
#define _Deref_pre_opt_bytecap_(size) ((void)0)
#define _Deref_pre_cap_c_(size) ((void)0)
#define _Deref_pre_opt_cap_c_(size) ((void)0)
#define _Deref_pre_bytecap_c_(size) ((void)0)
#define _Deref_pre_opt_bytecap_c_(size) ((void)0)
#define _Deref_pre_cap_x_(size) ((void)0)
#define _Deref_pre_opt_cap_x_(size) ((void)0)
#define _Deref_pre_bytecap_x_(size) ((void)0)
#define _Deref_pre_opt_bytecap_x_(size) ((void)0)
#define _Deref_pre_z_cap_(size) ((void)0)
#define _Deref_pre_opt_z_cap_(size) ((void)0)
#define _Deref_pre_z_bytecap_(size) ((void)0)
#define _Deref_pre_opt_z_bytecap_(size) ((void)0)
#define _Deref_pre_z_cap_c_(size) ((void)0)
#define _Deref_pre_opt_z_cap_c_(size) ((void)0)
#define _Deref_pre_z_bytecap_c_(size) ((void)0)
#define _Deref_pre_opt_z_bytecap_c_(size) ((void)0)
#define _Deref_pre_z_cap_x_(size) ((void)0)
#define _Deref_pre_opt_z_cap_x_(size) ((void)0)
#define _Deref_pre_z_bytecap_x_(size) ((void)0)
#define _Deref_pre_opt_z_bytecap_x_(size) ((void)0)
#define _Deref_pre_valid_cap_(size) ((void)0)
#define _Deref_pre_opt_valid_cap_(size) ((void)0)
#define _Deref_pre_valid_bytecap_(size) ((void)0)
#define _Deref_pre_opt_valid_bytecap_(size) ((void)0)
#define _Deref_pre_valid_cap_c_(size) ((void)0)
#define _Deref_pre_opt_valid_cap_c_(size) ((void)0)
#define _Deref_pre_valid_bytecap_c_(size) ((void)0)
#define _Deref_pre_opt_valid_bytecap_c_(size) ((void)0)
#define _Deref_pre_valid_cap_x_(size) ((void)0)
#define _Deref_pre_opt_valid_cap_x_(size) ((void)0)
#define _Deref_pre_valid_bytecap_x_(size) ((void)0)
#define _Deref_pre_opt_valid_bytecap_x_(size) ((void)0)
#define _Deref_pre_count_(size) ((void)0)
#define _Deref_pre_opt_count_(size) ((void)0)
#define _Deref_pre_bytecount_(size) ((void)0)
#define _Deref_pre_opt_bytecount_(size) ((void)0)
#define _Deref_pre_count_c_(size) ((void)0)
#define _Deref_pre_opt_count_c_(size) ((void)0)
#define _Deref_pre_bytecount_c_(size) ((void)0)
#define _Deref_pre_opt_bytecount_c_(size) ((void)0)
#define _Deref_pre_count_x_(size) ((void)0)
#define _Deref_pre_opt_count_x_(size) ((void)0)
#define _Deref_pre_bytecount_x_(size) ((void)0)
#define _Deref_pre_opt_bytecount_x_(size) ((void)0)
#define _Deref_pre_valid_ ((void)0)
#define _Deref_pre_opt_valid_ ((void)0)
#define _Deref_pre_invalid_ ((void)0)
#define _Deref_pre_notnull_ ((void)0)
#define _Deref_pre_maybenull_ ((void)0)
#define _Deref_pre_null_ ((void)0)
#define _Deref_pre_readonly_ ((void)0)
#define _Deref_pre_writeonly_ ((void)0)

#define _Deref_post_z_ ((void)0)
#define _Deref_post_opt_z_ ((void)0)
#define _Deref_post_cap_(size) ((void)0)
#define _Deref_post_opt_cap_(size) ((void)0)
#define _Deref_post_bytecap_(size) ((void)0)
#define _Deref_post_opt_bytecap_(size) ((void)0)
#define _Deref_post_cap_c_(size) ((void)0)
#define _Deref_post_opt_cap_c_(size) ((void)0)
#define _Deref_post_bytecap_c_(size) ((void)0)
#define _Deref_post_opt_bytecap_c_(size) ((void)0)
#define _Deref_post_cap_x_(size) ((void)0)
#define _Deref_post_opt_cap_x_(size) ((void)0)
#define _Deref_post_bytecap_x_(size) ((void)0)
#define _Deref_post_opt_bytecap_x_(size) ((void)0)
#define _Deref_post_z_cap_(size) ((void)0)
#define _Deref_post_opt_z_cap_(size) ((void)0)
#define _Deref_post_z_bytecap_(size) ((void)0)
#define _Deref_post_opt_z_bytecap_(size) ((void)0)
#define _Deref_post_z_cap_c_(size) ((void)0)
#define _Deref_post_opt_z_cap_c_(size) ((void)0)
#define _Deref_post_z_bytecap_c_(size) ((void)0)
#define _Deref_post_opt_z_bytecap_c_(size) ((void)0)
#define _Deref_post_z_cap_x_(size) ((void)0)
#define _Deref_post_opt_z_cap_x_(size) ((void)0)
#define _Deref_post_z_bytecap_x_(size) ((void)0)
#define _Deref_post_opt_z_bytecap_x_(size) ((void)0)
#define _Deref_post_valid_cap_(size) ((void)0)
#define _Deref_post_opt_valid_cap_(size) ((void)0)
#define _Deref_post_valid_bytecap_(size) ((void)0)
#define _Deref_post_opt_valid_bytecap_(size) ((void)0)
#define _Deref_post_valid_cap_c_(size) ((void)0)
#define _Deref_post_opt_valid_cap_c_(size) ((void)0)
#define _Deref_post_valid_bytecap_c_(size) ((void)0)
#define _Deref_post_opt_valid_bytecap_c_(size) ((void)0)
#define _Deref_post_valid_cap_x_(size) ((void)0)
#define _Deref_post_opt_valid_cap_x_(size) ((void)0)
#define _Deref_post_valid_bytecap_x_(size) ((void)0)
#define _Deref_post_opt_valid_bytecap_x_(size) ((void)0)
#define _Deref_post_count_(size) ((void)0)
#define _Deref_post_opt_count_(size) ((void)0)
#define _Deref_post_bytecount_(size) ((void)0)
#define _Deref_post_opt_bytecount_(size) ((void)0)
#define _Deref_post_count_c_(size) ((void)0)
#define _Deref_post_opt_count_c_(size) ((void)0)
#define _Deref_post_bytecount_c_(size) ((void)0)
#define _Deref_post_opt_bytecount_c_(size) ((void)0)
#define _Deref_post_count_x_(size) ((void)0)
#define _Deref_post_opt_count_x_(size) ((void)0)
#define _Deref_post_bytecount_x_(size) ((void)0)
#define _Deref_post_opt_bytecount_x_(size) ((void)0)
#define _Deref_post_valid_ ((void)0)
#define _Deref_post_opt_valid_ ((void)0)
#define _Deref_post_notnull_ ((void)0)
#define _Deref_post_maybenull_ ((void)0)
#define _Deref_post_null_ ((void)0)

#define _Deref_ret_z_ ((void)0)
#define _Deref_ret_opt_z_ ((void)0)
#define _Deref2_pre_readonly_ ((void)0)

//============================================================================
//   _Ret_ ---
//============================================================================

#define _Ret_opt_valid_ ((void)0)
#define _Ret_opt_z_ ((void)0)
#define _Ret_cap_(size) ((void)0)
#define _Ret_opt_cap_(size) ((void)0)
#define _Ret_bytecap_(size) ((void)0)
#define _Ret_opt_bytecap_(size) ((void)0)
#define _Ret_cap_c_(size) ((void)0)
#define _Ret_opt_cap_c_(size) ((void)0)
#define _Ret_bytecap_c_(size) ((void)0)
#define _Ret_opt_bytecap_c_(size) ((void)0)
#define _Ret_cap_x_(size) ((void)0)
#define _Ret_opt_cap_x_(size) ((void)0)
#define _Ret_bytecap_x_(size) ((void)0)
#define _Ret_opt_bytecap_x_(size) ((void)0)
#define _Ret_z_cap_(size) ((void)0)
#define _Ret_opt_z_cap_(size) ((void)0)
#define _Ret_z_bytecap_(size) ((void)0)
#define _Ret_opt_z_bytecap_(size) ((void)0)
#define _Ret_count_(size) ((void)0)
#define _Ret_opt_count_(size) ((void)0)
#define _Ret_bytecount_(size) ((void)0)
#define _Ret_opt_bytecount_(size) ((void)0)
#define _Ret_count_c_(size) ((void)0)
#define _Ret_opt_count_c_(size) ((void)0)
#define _Ret_bytecount_c_(size) ((void)0)
#define _Ret_opt_bytecount_c_(size) ((void)0)
#define _Ret_count_x_(size) ((void)0)
#define _Ret_opt_count_x_(size) ((void)0)
#define _Ret_bytecount_x_(size) ((void)0)
#define _Ret_opt_bytecount_x_(size) ((void)0)
#define _Ret_z_count_(size) ((void)0)
#define _Ret_opt_z_count_(size) ((void)0)
#define _Ret_z_bytecount_(size) ((void)0)
#define _Ret_opt_z_bytecount_(size) ((void)0)

//============================================================================
//   _Pre_/_Post_/_Prepost_ annotations ---
//============================================================================

#define _Pre_opt_z_ ((void)0)
#define _Pre_readonly_ ((void)0)
#define _Pre_writeonly_ ((void)0)
#define _Pre_cap_(size) ((void)0)
#define _Pre_opt_cap_(size) ((void)0)
#define _Pre_bytecap_(size) ((void)0)
#define _Pre_opt_bytecap_(size) ((void)0)
#define _Pre_cap_c_(size) ((void)0)
#define _Pre_opt_cap_c_(size) ((void)0)
#define _Pre_bytecap_c_(size) ((void)0)
#define _Pre_opt_bytecap_c_(size) ((void)0)
#define _Pre_cap_c_one_ ((void)0)
#define _Pre_opt_cap_c_one_ ((void)0)
#define _Pre_cap_m_(mult, size) ((void)0)
#define _Pre_opt_cap_m_(mult, size) ((void)0)
#define _Pre_cap_for_(param) ((void)0)
#define _Pre_opt_cap_for_(param) ((void)0)
#define _Pre_cap_x_(size) ((void)0)
#define _Pre_opt_cap_x_(size) ((void)0)
#define _Pre_bytecap_x_(size) ((void)0)
#define _Pre_opt_bytecap_x_(size) ((void)0)
#define _Pre_ptrdiff_cap_(ptr) ((void)0)
#define _Pre_opt_ptrdiff_cap_(ptr) ((void)0)
#define _Pre_z_cap_(size) ((void)0)
#define _Pre_opt_z_cap_(size) ((void)0)
#define _Pre_z_bytecap_(size) ((void)0)
#define _Pre_opt_z_bytecap_(size) ((void)0)
#define _Pre_z_cap_c_(size) ((void)0)
#define _Pre_opt_z_cap_c_(size) ((void)0)
#define _Pre_z_bytecap_c_(size) ((void)0)
#define _Pre_opt_z_bytecap_c_(size) ((void)0)
#define _Pre_z_cap_x_(size) ((void)0)
#define _Pre_opt_z_cap_x_(size) ((void)0)
#define _Pre_z_bytecap_x_(size) ((void)0)
#define _Pre_opt_z_bytecap_x_(size) ((void)0)
#define _Pre_valid_cap_(size) ((void)0)
#define _Pre_opt_valid_cap_(size) ((void)0)
#define _Pre_valid_bytecap_(size) ((void)0)
#define _Pre_opt_valid_bytecap_(size) ((void)0)
#define _Pre_valid_cap_c_(size) ((void)0)
#define _Pre_opt_valid_cap_c_(size) ((void)0)
#define _Pre_valid_bytecap_c_(size) ((void)0)
#define _Pre_opt_valid_bytecap_c_(size) ((void)0)
#define _Pre_valid_cap_x_(size) ((void)0)
#define _Pre_opt_valid_cap_x_(size) ((void)0)
#define _Pre_valid_bytecap_x_(size) ((void)0)
#define _Pre_opt_valid_bytecap_x_(size) ((void)0)
#define _Pre_count_(size) ((void)0)
#define _Pre_opt_count_(size) ((void)0)
#define _Pre_bytecount_(size) ((void)0)
#define _Pre_opt_bytecount_(size) ((void)0)
#define _Pre_count_c_(size) ((void)0)
#define _Pre_opt_count_c_(size) ((void)0)
#define _Pre_bytecount_c_(size) ((void)0)
#define _Pre_opt_bytecount_c_(size) ((void)0)
#define _Pre_count_x_(size) ((void)0)
#define _Pre_opt_count_x_(size) ((void)0)
#define _Pre_bytecount_x_(size) ((void)0)
#define _Pre_opt_bytecount_x_(size) ((void)0)
#define _Pre_ptrdiff_count_(ptr) ((void)0)
#define _Pre_opt_ptrdiff_count_(ptr) ((void)0)

#define _Post_maybez_ ((void)0)
#define _Post_cap_(size) ((void)0)
#define _Post_bytecap_(size) ((void)0)
#define _Post_count_(size) ((void)0)
#define _Post_bytecount_(size) ((void)0)
#define _Post_count_c_(size) ((void)0)
#define _Post_bytecount_c_(size) ((void)0)
#define _Post_count_x_(size) ((void)0)
#define _Post_bytecount_x_(size) ((void)0)
#define _Post_z_count_(size) ((void)0)
#define _Post_z_bytecount_(size) ((void)0)
#define _Post_z_count_c_(size) ((void)0)
#define _Post_z_bytecount_c_(size) ((void)0)
#define _Post_z_count_x_(size) ((void)0)
#define _Post_z_bytecount_x_(size) ((void)0)

#define _Prepost_opt_z_ ((void)0)
#define _Prepost_count_(size) ((void)0)
#define _Prepost_opt_count_(size) ((void)0)
#define _Prepost_bytecount_(size) ((void)0)
#define _Prepost_opt_bytecount_(size) ((void)0)
#define _Prepost_count_c_(size) ((void)0)
#define _Prepost_opt_count_c_(size) ((void)0)
#define _Prepost_bytecount_c_(size) ((void)0)
#define _Prepost_opt_bytecount_c_(size) ((void)0)
#define _Prepost_count_x_(size) ((void)0)
#define _Prepost_opt_count_x_(size) ((void)0)
#define _Prepost_bytecount_x_(size) ((void)0)
#define _Prepost_opt_bytecount_x_(size) ((void)0)
#define _Prepost_valid_ ((void)0)
#define _Prepost_opt_valid_ ((void)0)

//============================================================================
//   _Deref_<both> ---
//============================================================================

#define _Deref_prepost_z_ ((void)0)
#define _Deref_prepost_opt_z_ ((void)0)
#define _Deref_prepost_cap_(size) ((void)0)
#define _Deref_prepost_opt_cap_(size) ((void)0)
#define _Deref_prepost_bytecap_(size) ((void)0)
#define _Deref_prepost_opt_bytecap_(size) ((void)0)
#define _Deref_prepost_cap_x_(size) ((void)0)
#define _Deref_prepost_opt_cap_x_(size) ((void)0)
#define _Deref_prepost_bytecap_x_(size) ((void)0)
#define _Deref_prepost_opt_bytecap_x_(size) ((void)0)
#define _Deref_prepost_z_cap_(size) ((void)0)
#define _Deref_prepost_opt_z_cap_(size) ((void)0)
#define _Deref_prepost_z_bytecap_(size) ((void)0)
#define _Deref_prepost_opt_z_bytecap_(size) ((void)0)
#define _Deref_prepost_valid_cap_(size) ((void)0)
#define _Deref_prepost_opt_valid_cap_(size) ((void)0)
#define _Deref_prepost_valid_bytecap_(size) ((void)0)
#define _Deref_prepost_opt_valid_bytecap_(size) ((void)0)
#define _Deref_prepost_valid_cap_x_(size) ((void)0)
#define _Deref_prepost_opt_valid_cap_x_(size) ((void)0)
#define _Deref_prepost_valid_bytecap_x_(size) ((void)0)
#define _Deref_prepost_opt_valid_bytecap_x_(size) ((void)0)
#define _Deref_prepost_count_(size) ((void)0)
#define _Deref_prepost_opt_count_(size) ((void)0)
#define _Deref_prepost_bytecount_(size) ((void)0)
#define _Deref_prepost_opt_bytecount_(size) ((void)0)
#define _Deref_prepost_count_x_(size) ((void)0)
#define _Deref_prepost_opt_count_x_(size) ((void)0)
#define _Deref_prepost_bytecount_x_(size) ((void)0)
#define _Deref_prepost_opt_bytecount_x_(size) ((void)0)
#define _Deref_prepost_valid_ ((void)0)
#define _Deref_prepost_opt_valid_ ((void)0)

#define _Deref_out_z_cap_c_(size) ((void)0)
#define _Deref_inout_z_cap_c_(size) ((void)0)
#define _Deref_out_z_bytecap_c_(size) ((void)0)
#define _Deref_inout_z_bytecap_c_(size) ((void)0)
#define _Deref_inout_z_ ((void)0)

#endif // #ifndef YAGLPP_NO_MSVC_H
